name: Build and Deploy

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        target:
          - chip: esp32c6
            flash_freq: 80m
          - chip: esp32h2
            flash_freq: 48m

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: ${{ matrix.target.chip }}
          path: .
          command: |
            idf.py build &&
            idf.py merge-bin -o co2_sensor_${{ matrix.target.chip }}.bin -f raw

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: co2_sensor_${{ matrix.target.chip }}
          path: build/co2_sensor_${{ matrix.target.chip }}.bin

  deploy-pages:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download ESP32-C6 binary
        uses: actions/download-artifact@v4
        with:
          name: co2_sensor_esp32c6
          path: docs/bin_latest

      - name: Download ESP32-H2 binary
        uses: actions/download-artifact@v4
        with:
          name: co2_sensor_esp32h2
          path: docs/bin_latest

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
